#ifndef MORSEVOICE_H_
#define MORSEVOICE_H_

/******************************************************************************************************************************
 *  Software for the Morserino-32 (M32) multi-functional Morse code machine, based on the Heltec WiFi LORA (ESP32) module   ***
 *  Copyright (C) 2018-2025  Willi Kraml, OE1WKL                                                                            ***
 *
 *  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 *  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *****************************************************************************************************************************/

#include <Arduino.h>

// V9.0 audio accessibility (M32 Pocket "Accessibility" build, CONFIG_AUDIO_A11Y).
// Speaks menu / preference / option entries as pre-rendered MP3 clips played on-device.
// announce() is a no-op on builds without CONFIG_AUDIO_A11Y, so call sites stay clean.
namespace MorseVoice
{
  // Request announcement of a firmware-facing UI string (menu display text, spoken pref
  // label, option value, numeric value...). Non-blocking and debounced: the latest request
  // wins, and tick() starts playback once navigation settles. Silent if the string has no
  // clip (e.g. an out-of-range number). No-op without CONFIG_AUDIO_A11Y.
  void announce(const String& text);
  // Append another clip to the current (still-debouncing) utterance, e.g. the value after the
  // heading: announce("Serial Output"); announceMore("Nothing"); -> speaks both in sequence.
  void announceMore(const String& text);
  // Append a single CHARACTER, spelled out: NATO phonetic for letters, the spoken name for
  // digits and punctuation, "pro sign" + two phonetics for a prosign. Takes the raw firmware
  // character (an uppercase prosign code, NOT the cleanUpProSigns() form), so a Koch lesson
  // character can be voiced: announceMore("21"); announceMoreChar("y"); -> "21, Yankee".
  void announceMoreChar(const String& ch);
  // Drive async playback (advance/finish current clip, fire the settled utterance). Must be
  // polled frequently from the menu / preference loops.
  void tick();
  // Interrupt + clear any current/pending announcement (e.g. when leaving the menu).
  void stop();

  // ---- the voice store itself ------------------------------------------------------------
  // Without its clips this build says nothing at all, and for the operator it exists for a
  // mute device is indistinguishable from a dead one. So the boot path asks whether the
  // store is really there, and reports it on channels that cannot go missing with it.

  // True when nothing is wrong with the clip store: the clips are there AND they are this
  // firmware's clips. Cheap (a few SPIFFS.exists() probes plus one small read) and cached,
  // so call it freely. Always true without CONFIG_AUDIO_A11Y.
  bool clipStoreOk();
  // True when there are clips worth playing - store fine, OR a pack that does not match
  // this firmware (most of it still plays; the operator hears the alarm and is told which
  // entries are new only by their silence). False only when there is nothing there at all.
  bool clipStoreUsable();
  // The <= 24-character display line for a sighted helper, or nullptr when nothing is wrong.
  // A string rather than a bool at the call site so a further verdict needs no change
  // outside MorseVoice.cpp.
  const char* clipStoreDisplayText();
  // Sound the alarm: a short two-tone pattern on the sidetone, which is generated by the
  // firmware itself and owes nothing to SPIFFS. Deliberately NOT speech and NOT Morse -
  // the clips are what is missing, and the audience includes complete CW beginners.
  // Non-blocking: driven by the same tick() as the clips, cut by the same stop().
  // No-op when the store is fine, and without CONFIG_AUDIO_A11Y.
  void warnClipStore();
}

#endif /* #ifndef MORSEVOICE_H_ */
