#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_inventories.py -- regenerate the machine-derived inventories.

Writes, next to this script:
  inventory-menu-terms.md   on-device labels used in the manual, with the
                            firmware gating that says whether they differ
                            between variants
  inventory-images.md       image references and their variant classification
  inventory-tables.md       every table, with the properties session 2 needs
                            to decide which ones to linearise for the a11y build
  inventory-morse.md        every occurrence of Morse written as symbols

inventory-ambiguous.md is deliberately NOT generated: it is a judgement
document and is maintained by hand.

Usage:  python3 make_inventories.py
"""
import os
import re
from collections import Counter

import firmware_terms as ft
import tagmap

HERE = os.path.dirname(os.path.abspath(__file__))
LANGS = ("en", "de")


def sources():
    return {l: open(os.path.join(tagmap.MANUAL, "manual_%s.md" % l),
                    encoding="utf-8").read().split("\n") for l in LANGS}


def section_at(sections, line):
    best = None
    for s in sections:
        if s["line"] <= line:
            best = s
        else:
            break
    return best["title"] if best else "(front matter)"


def find_term(lines, term):
    """Line numbers where the term appears as a device label.

    The manual marks device labels in bold or italics most of the time, but not
    always, so plain occurrences count too -- with a word boundary so that
    'Random' does not match 'Randomly'.

    Matched against the *joined* text rather than line by line, because the
    German source wraps at ~72 characters and splits terms across lines
    ("*Upload\\nFile*"). A line-by-line search silently misses those and makes
    the two languages look divergent when they are not.
    """
    words = [re.escape(w) for w in term.split()]
    pat = re.compile(r"(?<![A-Za-z0-9])" + r"[\s*_]+".join(words)
                     + r"(?![A-Za-z0-9])")
    text = "\n".join(lines)
    starts, pos = [], 0
    for line in lines:
        starts.append(pos)
        pos += len(line) + 1

    def line_of(idx):
        lo, hi = 0, len(starts) - 1
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if starts[mid] <= idx:
                lo = mid
            else:
                hi = mid - 1
        return lo + 1

    return sorted({line_of(m.start()) for m in pat.finditer(text)})


# ---------------------------------------------------------------- menu terms
def menu_terms(src):
    rows = []
    seen = set()
    groups = (("menu entry", [(t, g) for t, g in ft.menu_entries()]),
              ("preference", [(t, g) for t, _, g in ft.preferences()]),
              ("action item", [(t, g) for t, g in ft.extra_items()]))
    for kind, items in groups:
        for term, guards in items:
            key = (kind, term)
            if key in seen:
                continue
            seen.add(key)
            variants = ft.variants_for(guards)
            hits = {l: find_term(src[l], term) for l in LANGS}
            rows.append({"kind": kind, "term": term, "guards": guards,
                         "variants": variants, "hits": hits})
    # option values that differ per variant are the interesting ones
    values = []
    per_label = {}
    for label, opts, guards in ft.preferences():
        per_label.setdefault(label, []).append((opts, guards))
    for label, variants in per_label.items():
        if len(variants) > 1:
            values.append((label, variants))
    return rows, values


def write_menu_terms(src):
    rows, differing_values = menu_terms(src)
    out = []
    w = out.append
    w("# Inventory: on-device terms used in the manual\n")
    w("Generated by `make_inventories.py`. Do not edit by hand.\n")
    w("Every menu entry, preference label and action item the firmware defines,")
    w("with the build flags that gate it and the lines of each manual where the")
    w("string occurs. **Nothing here is changed yet** -- session 2 introduces the")
    w("placeholder mechanism that resolves these from a per-variant terminology")
    w("file; this is the list it has to cover.\n")
    w("The variant column comes from the firmware's own `#ifdef`s, not from the")
    w("prose, so it is the authority when the two disagree.\n")

    flagged = [r for r in rows if len(r["variants"]) < 3]
    w("## Terms that do NOT exist on every variant (%d)\n" % len(flagged))
    w("These are the ones a per-variant terminology file has to handle. A term")
    w("with no manual hits is not documented at all -- also worth knowing.\n")
    w("| Kind | Term | Exists on | Gated by | EN lines | DE lines |")
    w("|---|---|---|---|---|---|")
    for r in sorted(flagged, key=lambda r: (r["kind"], r["term"])):
        w("| %s | `%s` | %s | `%s` | %s | %s |"
          % (r["kind"], r["term"], ", ".join(r["variants"]),
             ", ".join(r["guards"]) or "-",
             ", ".join(map(str, r["hits"]["en"])) or "*not documented*",
             ", ".join(map(str, r["hits"]["de"])) or "*not documented*"))
    w("")

    if differing_values:
        w("## Preferences whose option *values* differ per variant (%d)\n"
          % len(differing_values))
        w("Same label on both devices, different set of choices behind it --")
        w("the case a naive label-only terminology file would miss.\n")
        for label, variants in differing_values:
            w("**`%s`**\n" % label)
            for opts, guards in variants:
                w("- on %s (`%s`): %s"
                  % (", ".join(ft.variants_for(guards)),
                     ", ".join(guards) or "-",
                     ", ".join("`%s`" % o for o in opts) if opts
                     else "*values not on a single source line; check by hand*"))
            w("")

    universal = [r for r in rows if len(r["variants"]) == 3]
    undocumented = [r for r in universal if not r["hits"]["en"]]
    w("## Terms present on every variant (%d)\n" % len(universal))
    w("No terminology entry needed. Listed for completeness, and because the")
    w("ones with no manual hits are undocumented device labels.\n")
    w("| Kind | Term | EN lines | DE lines |")
    w("|---|---|---|---|")
    for r in sorted(universal, key=lambda r: (r["kind"], r["term"])):
        w("| %s | `%s` | %s | %s |"
          % (r["kind"], r["term"],
             ", ".join(map(str, r["hits"]["en"][:8]))
             + (" …" if len(r["hits"]["en"]) > 8 else "") or "*not documented*",
             ", ".join(map(str, r["hits"]["de"][:8]))
             + (" …" if len(r["hits"]["de"]) > 8 else "") or "*not documented*"))
    w("")
    w("%d of these never appear in the English manual: %s.\n"
      % (len(undocumented),
         ", ".join("`%s`" % r["term"] for r in undocumented) or "none"))
    return "\n".join(out)


# -------------------------------------------------------------------- images
IMAGE_CLASS = {
    "images/m32pocket.jpg": ("pocket",
                             "Photo of the M32 Pocket, under the Pocket "
                             "connectors section (already tagged)."),
    "images/m32_2nd_edition.jpg": ("classic",
                                   "Photo of the 2nd edition, under its own "
                                   "section (already tagged)."),
    "images/m32_1st_edition.jpg": ("classic",
                                   "Photo of the 1st edition, under its own "
                                   "section (already tagged)."),
    "images/status_line.png": ("classic",
                               "Status line screenshot. The manual's own note "
                               "says it shows the older Morserinos and that the "
                               "Pocket 'is similar' -- so it is an OLED "
                               "screenshot standing in for both. Needs a Pocket "
                               "counterpart before it can be tagged."),
    "images/M32_logo.png": ("common",
                            "Used by title.html / title_de.html, not from the "
                            "Markdown."),
}


def write_images(src):
    out = []
    w = out.append
    w("# Inventory: images\n")
    w("Generated by `make_inventories.py`. Do not edit by hand.\n")
    found = {}
    for lang in LANGS:
        for n, line in enumerate(src[lang], 1):
            for m in re.finditer(r"!\[([^\]]*)\]\(([^)]+)\)", line):
                found.setdefault(m.group(2), {"alt": m.group(1), "at": {}})
                found[m.group(2)]["at"].setdefault(lang, []).append(n)
    w("`images/` holds %d files; %d are referenced from the Markdown and one "
      "(`M32_logo.png`) from the title pages.\n"
      % (len(IMAGE_CLASS), len(found)))
    w("| Image | Proposed class | EN line | DE line | Alt text | Notes |")
    w("|---|---|---|---|---|---|")
    for path, rec in sorted(found.items()):
        cls, note = IMAGE_CLASS.get(path, ("unknown", ""))
        w("| `%s` | **%s** | %s | %s | %s | %s |"
          % (path, cls,
             ", ".join(map(str, rec["at"].get("en", []))) or "-",
             ", ".join(map(str, rec["at"].get("de", []))) or "-",
             "*(none)*" if not rec["alt"] else rec["alt"], note))
    for path, (cls, note) in sorted(IMAGE_CLASS.items()):
        if path not in found:
            w("| `%s` | **%s** | - | - | - | %s |" % (path, cls, note))
    w("")
    missing_alt = [p for p, rec in found.items() if not rec["alt"].strip()]
    w("## Where this stands\n")
    w("- **Alt text: %s.** %s"
      % ("done" if not missing_alt else "%d image(s) still missing it" % len(missing_alt),
         "Each image says what it shows and notes that the numbers match the "
         "table below; pandoc now declares schema:accessibilityFeature "
         "alternativeText in the EPUB."
         if not missing_alt else "Missing on: " + ", ".join(missing_alt)))
    w("- Three of the four referenced images are already inside a variant div,")
    w("  so per-variant image paths are not strictly needed for them -- the")
    w("  surrounding tag already removes them.")
    w("- The M32 Pocket photo is followed by a `{.pocket-a11y}` block describing")
    w("  the device by touch, since that is the only photo a reader of the")
    w("  accessibility edition meets. It is drafted and marked in the source with")
    w("  a TODO: the touch-paddle and FN-button positions need checking against a")
    w("  real device.")
    w("- `status_line.png` is the one still-open case: an OLED screenshot shown")
    w("  to Pocket readers too, with a note apologising for it. A Pocket")
    w("  screenshot plus a per-variant path (or two tagged image references)")
    w("  would let the note go away.")
    return "\n".join(out)


# -------------------------------------------------------------------- tables
def tables_of(lines):
    out, cur = [], None
    section, sections = "(front matter)", []
    for n, line in enumerate(lines, 1):
        h = re.match(r"^(#{1,6}) +(.*?)\s*(\{[^}]*\})?\s*$", line)
        if h:
            section = h.group(2).strip()
        if line.lstrip().startswith("|"):
            if cur is None:
                cur = {"start": n, "section": section, "rows": [], "cols": 0}
            cells = [c for c in line.strip().strip("|").split("|")]
            cur["rows"].append(cells)
            cur["cols"] = max(cur["cols"], len(cells))
        elif cur is not None:
            cur["end"] = n - 1
            out.append(cur)
            cur = None
    if cur:
        cur["end"] = len(lines)
        out.append(cur)
    return out


def classify_table(t):
    """(layout_only, screen_reader_verdict, note)"""
    header = t["rows"][0] if t["rows"] else []
    heads = [h.strip().lower() for h in header]
    # a grid that repeats the same pair of columns is a layout table
    if t["cols"] >= 4 and len(heads) >= 4:
        first_pair = heads[:2]
        repeats = all(heads[i:i + 2] == first_pair
                      for i in range(0, len(heads) - 1, 2))
        if repeats:
            return (True, "poor",
                    "Repeats the same column pair %d times across the page. "
                    "Read linearly it becomes 'Lesson 1, Character m, Lesson 18, "
                    "Character 0, Lesson 35, Character 7' -- three unrelated "
                    "lessons per row. Linearise for the a11y build."
                    % (len(heads) // 2))
    if t["cols"] <= 1:
        return (True, "poor", "Single column; not really a table.")
    return (False, "ok",
            "Ordinary data table: one subject per row, header row present.")


def write_tables(src):
    out = []
    w = out.append
    w("# Inventory: tables\n")
    w("Generated by `make_inventories.py`. Do not edit by hand.\n")
    en_t, de_t = tables_of(src["en"]), tables_of(src["de"])
    w("English: **%d tables**. German: **%d tables**. %s\n"
      % (len(en_t), len(de_t),
         "Counts and column shapes match table for table."
         if [t["cols"] for t in en_t] == [t["cols"] for t in de_t]
         else "**Counts or shapes differ -- see the parallelism check.**"))
    w("## Merged cells\n")
    w("Pandoc's pipe tables **cannot express merged cells at all**, and every")
    w("table in this manual is a pipe table, so the answer is uniform: *no table")
    w("has merged cells*. That question is settled for the whole document and")
    w("does not need a per-table column.\n")
    w("What varies is whether a table is a data table or a layout grid.\n")
    w("## Tables that read badly linearly (%d)\n"
      % sum(1 for t in en_t if classify_table(t)[0]))
    w("These are the ones session 2 should linearise for the a11y build.\n")
    w("| EN lines | Section | Cols | Rows | Why |")
    w("|---|---|---|---|---|")
    for t, d in zip(en_t, de_t):
        layout, verdict, note = classify_table(t)
        if layout:
            w("| %d–%d | %s | %d | %d | %s |"
              % (t["start"], t["end"], t["section"], t["cols"],
                 len(t["rows"]) - 2, note))
    w("")
    w("## All tables\n")
    w("| EN lines | DE lines | Section | Cols | Data rows | Layout only | Screen reader |")
    w("|---|---|---|---|---|---|---|")
    for t, d in zip(en_t, de_t):
        layout, verdict, _ = classify_table(t)
        w("| %d–%d | %d–%d | %s | %d | %d | %s | %s |"
          % (t["start"], t["end"], d["start"], d["end"], t["section"],
             t["cols"], max(len(t["rows"]) - 2, 0),
             "**yes**" if layout else "no", verdict))
    w("")
    w("## Other screen-reader notes\n")
    w("- Pandoc emits `<th>` for the header row but **without a `scope`")
    w("  attribute**; the briefing's session-2 list already has scoped `<th>`")
    w("  on it, and it applies to all %d tables." % len(en_t))
    w("- Several description cells carry a literal `<br>` to force a line break")
    w("  inside the cell. That is fine visually and harmless to a screen reader,")
    w("  but it means cell text is not always one flowing sentence.")
    w("- The preference tables now carry row markers (an empty variant span at")
    w("  the start of the first cell). A filter that drops those rows must drop")
    w("  the whole `Row`, not just the span.")
    return "\n".join(out)


# --------------------------------------------------------------------- morse
def write_morse(src):
    out = []
    w = out.append
    w("# Inventory: Morse written as symbols\n")
    w("Generated by `make_inventories.py`. Do not edit by hand.\n")
    w("Session 2 wraps these in a `.morse` span so the a11y build can emit a")
    w("spoken dit/dah form alongside the visual symbols. The result of actually")
    w("counting them is the headline: **there are two sites per language, in two")
    w("different notations.** This is a much smaller job than the briefing")
    w("anticipated.\n")

    w("## How these were found\n")
    w("A Morse token is a run of 2 to 8 element characters, bounded by")
    w("non-word characters, that contains **at least one dit and at least one")
    w("dah**. Requiring both is what separates real Morse from the look-alikes")
    w("in this document: the ellipsis in `n is 1 .. 8`, the `---` of a table")
    w("rule, and the escaped filename `*m32\\_Vx.y\\[\\...\\].bin*` are all")
    w("single-element runs and drop out. Before matching, `\\.` is normalised to")
    w("`.` and `\\_` / `_` to `-`, so both notations are searched with one")
    w("pattern.\n")

    def morse_hits(lines):
        hits = []
        token = re.compile(r"(?<![A-Za-z0-9])([.\-]{2,8})(?![A-Za-z0-9])")
        for n, line in enumerate(lines, 1):
            if re.fullmatch(r"[\s|:\-]*", line):
                continue                      # table rule / blank
            norm = line.replace("\\.", ".").replace("\\_", "-").replace("_", "-")
            for m in token.finditer(norm):
                t = m.group(1)
                if "." in t and "-" in t:
                    hits.append((n, m.group(1), line.strip()))
        return hits

    w("## Occurrences\n")
    w("| Lang | Line | Token(s) | Notation | Source line |")
    w("|---|---|---|---|---|")
    total = {}
    for lang in LANGS:
        hits = morse_hits(src[lang])
        total[lang] = len(hits)
        by_line = {}
        for n, tok, text in hits:
            by_line.setdefault(n, {"toks": [], "text": text})["toks"].append(tok)
        for n, rec in sorted(by_line.items()):
            raw = src[lang][n - 1]
            notation = ("dot + underscore, backslash-escaped"
                        if "\\_" in raw or "\\." in raw else "dot + hyphen")
            w("| %s | %d | %s | %s | `%s` |"
              % (lang.upper(), n,
                 " ".join("`%s`" % t for t in rec["toks"]), notation,
                 rec["text"][:90].replace("|", "\\|")))
    w("")
    w("**Totals: %d tokens in EN, %d in DE**, on %d source lines per language.\n"
      % (total["en"], total["de"], 2))
    w("## Related notations found on the way\n")
    prosign = re.compile(r"\\?<(as|ka|kn|sk|ve|bk|err|hh|ar|bt)>", re.I)
    pcount = {l: sum(len(prosign.findall(x)) for x in src[l]) for l in LANGS}
    w("**Prosigns in angle brackets** -- `<ka>`, `<sk>`, `<as>`, `<bk>`, `<err>`,")
    w("`\\<HH>`: %d occurrences in EN, %d in DE. Not Morse symbols, but the other"
      % (pcount["en"], pcount["de"]))
    w("notation a screen reader will mangle -- verified that pandoc escapes them")
    w("to `&lt;ka&gt;`, so they survive into the HTML intact; how a screen reader")
    w("pronounces them is a session-2 question. The firmware already has an")
    w("answer for the spoken form: the voice engine says \"pro sign\" followed by")
    w("the two NATO letters (see `extract_voice_strings.py`), which is the")
    w("obvious model to copy.\n")
    dd = {l: sum(1 for x in src[l] if re.search(r"\b(dit|dah)s?\b", x, re.I))
          for l in LANGS}
    w("**`dit` / `dah` spelled out in prose** -- %d lines in EN, %d in DE. This"
      % (dd["en"], dd["de"]))
    w("is the form the a11y build wants to emit for the symbol sites above, so")
    w("the vocabulary is already established in the text.\n")
    w("## Recommendation\n")
    w("With only two sites, wrapping them by hand in session 2 is trivial. The")
    w("thing worth deciding is the *notation* going forward: the manual uses dot")
    w("+ underscore in one place and dot + hyphen in the other, for no visible")
    w("reason. Picking one (dot + hyphen reads better and needs no backslash")
    w("escaping) would be a one-line change and makes any future `.morse` filter")
    w("a single pattern instead of two.")
    return "\n".join(out)


def main():
    src = sources()
    for name, text in (("inventory-menu-terms.md", write_menu_terms(src)),
                       ("inventory-images.md", write_images(src)),
                       ("inventory-tables.md", write_tables(src)),
                       ("inventory-morse.md", write_morse(src))):
        path = os.path.join(HERE, name)
        open(path, "w", encoding="utf-8").write(text.rstrip() + "\n")
        print("wrote %s (%d lines)" % (name, text.count("\n") + 1))


if __name__ == "__main__":
    main()
